variables:
  - name: user
    type:
      type_name: map
      params:
        - type_name: string
        - type_name: dyn
  - name: items
    type:
      type_name: list
      params:
        - type_name: dyn
extensions:
  - name: bindings
    version: "latest"
  - name: "encoders"
  - name: "lists"
    version: "latest"
  - name: "math"
  - name: "sets"
  - name: "strings"
    version: "latest"
  - name: "regex"
  - name: "two-var-comprehensions"
